
server:
  port: 8081
spring:
 application:
  name: SpringBootOAuth
security:
  oauth2:
   client:
    clientId: 1870476700070105
    clientSecret: ●●●●●●●●
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
   userInfoUri: https://graph.facebook.com/me